Import('env')
env = env.Clone()

env.Append(CCFLAGS=['-O2', '-std=c99'])
env.Append(CPPPATH=['.', '#alice/include'])
env.Append(LIBPATH=['#alice/build/lib'])
env.Append(LIBS=['alice', 'albase'])

if env['PLATFORM'] == 'darwin':
	env.Append(FRAMEWORKS=['Foundation', 'AppKit', 'Lua', 'SDL2', 'SDL2_image', 'OpenGL'])

if env['PLATFORM'] == 'raspi':
	env.Append(CCFLAGS=['-D_GNU_SOURCE', '-DRASPI'])
	env.Append(CPPPATH=['/opt/vc/include', '/opt/vc/include/interface/vcos/pthreads'])
	env.Append(LIBPATH=['/opt/vc/lib'])
	env.Append(LIBS=['lua5.2', 'SDL2', 'SDL2_image', 'GLESv2'])


sources = ['main.c']

env.Program('alice-demo', sources)
env.Install('demo.lua')
